<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/01 15:26:52

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;port=3306;dbname=svc_hrm',
  'username' => 'admin',
  'password' => 'admin123',
  'attributes' => 
  array (
    'export' => 'tables',
  ),
  'name' => 'doctrine',
)),);
